name: DungeonGeneratorPractice
version: '1.0'
main: com.raeden.dungeon_practice.DungeonGeneratorPractice
api-version: '1.20'
commands:
  dungeon:
    description: dungeon basic command
    aliases: dg
